### ISSUE TITLE
Issue on page /DynamoVersion/civil3d.html

### ISSUE THREAD

**Issue by 2158112033** [chuongmep/Awesome-Dynamo#6]
Your issue content here.

**Comment by chuongmep** [comment]
Hi @2158112033, thanks for your comments, what the problem with content of civil, can help me explain more ?

**Comment by 2158112033** [comment]
Hi Boss, how can i read this book thanks

**Comment by chuongmep** [comment]
Hi @2158112033 you can select any category you like and learn it, some category of this e-book still in process now.

**Comment by vuonghongngoc** [comment]
![image](https://user-images.githubusercontent.com/115394403/194745644-f28eb6c4-de3f-4231-9dc3-735d7daf3240.png)

**Comment by vuonghongngoc** [comment]
> Hi Boss, how can i read this book thanks

You click " Awesome-Dynamo". You will find the courses

**Comment by 2158112033** [comment]
Thank you, boss, Do You have any MEP Scripts Regards.
    On Sunday, October 9, 2022 at 11:18:51 AM GMT+3, vuonghongngoc ***@***.***> wrote:  
 
 



Hi Boss, how can i read this book thanks


You click " Awesome-Dynamo". You will find the courses

**Comment by chuongmep** [comment]
@2158112033 you can find it at https://chuongmep.github.io/Awesome-Dynamo/DynamoScripts/dynscripts.html.
This is just the beginning of a big project, I hope you'll be a part of it.
